### ISSUE TITLE
Support XCM v1

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/PINT#260]
## Issue summary

- [ ] Update substrate + polkadot (0.9.9), which will introduce v1
- [ ] use `xcm::latest`
- [ ] rename all types accordingly
- [ ] Make `Location::Null` a noop

## Other information and links

-  https://github.com/paritytech/polkadot/pull/2815#issuecomment-893297725
