### ISSUE TITLE
Weights checklist

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#261]
## Issue summary

Tracking all weights

### asset-index
- [x] add-asset
- [x] remove_asset
- [x] register_asset
- [x] set_metadata 
- [x] deposit
- [x] withdraw
- [x] complete_withdraw
- [x] unlock

### committee
- [x] propose
- [x] vote
- [x] close
- [x] add_constituent

### local-treasury

- [x] withdraw

### price-feed

- [x] map_asset_price_feed
- [x] unmap_asset_price_feed

### remote-asset-manager

- [ ] send_bond
- [ ] send_add_proxy
- [ ] update_staking_weights
- [ ] update_statemint_assets_weights
- [ ] enable_statemint_xcm
- [ ] disable_statemint_xcm
- [ ] set_statemint_config
- [ ] transfer_to_statemint

### saft-registry

- [x] report_nav
- [x] convert_to_liquid

## Other information and links

-  #230

**Comment by dutterbutter** [comment]
@clearloop @mattsse Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/PINT-6050fdbefec7550019a6100a/issues/ChainSafe/PINT/261?planning-poker)

**Comment by mattsse** [comment]
blocked until xcm benchmarking is supported
